version: 2
jobs:
  build:
    docker:

      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/noissefnoc/go-netflix-activities
    steps:
      - checkout

      - run:
          name: Install dependency modules
          command: make deps

      - run:
          name: Install coverage tool and static analysis
          command: |
            go get github.com/axw/gocov/gocov
            go get github.com/mattn/goveralls
            go get -u github.com/alecthomas/gometalinter
            gometalinter --install

      - run:
          name: Run unit tests
          command: make test

      - run:
          name: Run coverage and static analysis
          command: |
            gometalinter --deadline 30s ./...
            goveralls -v -service=circle-ci -repotoken $COVERALLS_TOKEN ./...

      - run:
          name: Build module
          command: make
